# -*- coding: utf-8 -*-
"""Streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pE44Tq8lpuFHupLdS1DDGiO9Roz_31ZN
"""

!pip install streamlit openai

import streamlit as st
import openai
import os

openai.api_key = "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"

def correct_grammar(input_string):
    response = openai.Completion.create(
        engine="text-davinci-003",
        prompt="Correct this to standard English: " + input_string + "\n",
        max_tokens=60,
        top_p=1.0,
        frequency_penalty=0.0,
        presence_penalty=0.0,
        temperature=0.0,
        stop="\n\n",
    )
    answer = response.choices[0].text.strip()
    return answer

def main():
    st.title("Grammar Correction")

    input_string = st.text_input("Enter a sentence:")
    if input_string:
        output = correct_grammar(input_string)
        st.text(f"Input: {input_string}")
        st.text(f"Output: {output}")

if __name__ == "__main__":
    main()